alias diary-build="docker-compose build"
alias frontend="diary-build frontend && docker-compose up frontend"
alias backend="diary-build backend && docker-compose up backend"
alias backbash="docker-compose exec backend bash"
alias frontbash="docker-compose exec frontend bash"
alias backlogs="docker logs -f backend --tail 100"